import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import AntdRegistry from "@/lib/AntdRegistry";

import HeaderComponent from "@/components/HeaderComponent";
import StoreProvider from "@/providers/StoreProvider";
import AntdProvider from "@/providers/AntdProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ background: "#ccc" }}>
        <StoreProvider>
          <AntdProvider>
            <AntdRegistry>
              <HeaderComponent />
              {children}
            </AntdRegistry>
          </AntdProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
