import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "./globals.css";

import AntdRegistry from '@/lib/AntdRegistry'

import HeaderComponent from '@/components/HeaderComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ background: '#ccc' }}>
        <AntdRegistry>
          <HeaderComponent></HeaderComponent>
          {children}</AntdRegistry>
      </body>
    </html>
  )
}
